
server:  port: 8083
spring:  application:    name: hsn-details-service
      #######################------Database related propertises-------########################
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting
    username: postgres
    password: Vasavi
    
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dailect: org.hibernate.dialect.PostgreSQL81Dialect      
    hibernate:
      ddl-auto: update
    show-sql: true
    
     #######################------Eureka server related propertises-------########################
eureka:
  serviceUrl:
      defaultZone:http//localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:    fetch-registry: true
    register-with-eureka: true

logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/hsn-details.log
    level:
      com.otsi.retail.hsnDetails.service: DEBUG  
    
