
server:  port: 8083
spring:  application:    name: hsn-details-service
      #######################------Database related propertises-------########################
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting
    username: postgres
    password: Vasavi
    
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dailect: org.hibernate.dialect.PostgreSQL81Dialect      
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
     #######################------Eureka server related propertises-------########################
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost


logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/hsn-details.log
    level:
      com.otsi.retail.hsnDetails.service: DEBUG  
    
