
server:  port: 8083
spring:  application:    name: hsn-details-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting
    username: postgres
    password: 12345
    
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dailect: org.hibernate.dialect.PostgreSQL81Dialect      
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  serviceUrl:
      defaultZone:http//localhost:8761/eureka/
  client:    fetch-registry: true
    register-with-eureka: true

logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/hsn-details.log
