
server:
  port: 8083
spring:
  application:
    name: hsn-details-service
      #######################------Database related propertises-------########################
  datasource:
    url: jdbc:postgresql://hsn-details-pos:5432/accounting
    username: postgres
    password: Otsi@123
    
  jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
     #######################------Eureka server related propertises-------########################

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.100.143.45:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/hsn-details.log
    level:
      com.otsi.retail.hsnDetails.service: DEBUG  
    
getStoreDetails_url: http://usermanagement:8084/store/storeList